[package]
name = "renovate-test"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = "1.0.219"
tokio = { version = "1.45.1", features = ["full"] }


[dependencies.test-crate]
git = "https://github.com/okkero/test-crate.git"
rev = "4bdf8f871e408669c8e9d9138352490930814525"