[package]
name = "renovate-test"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = "1.0.219"
tokio = { version = "1.45.1", features = ["full"] }


[dependencies.test-crate]
git = "ssh://git@github.com/okkero/test-crate.git"
rev = "0eaa423d83c9891ce6b7d85d828529ed24e4639d"
