[package]
name = "renovate-test"
version = "0.1.0"
edition = "2024"

[dependencies]


[dependencies.session]
git = "ssh://git@github.com/Fredrik-Louisa/rust-common.git"
rev = "4e7a633e8b6e0966c3f98c6c5f45684103c44e6d"